### ISSUE TITLE
Specify that students should use Postman Web App instead of locally

### ISSUE THREAD

**Issue by lazyplatypus** [bitprj/Intro-To-Serverless#253]
Change the curriculum

**Comment by dtetreau251** [comment]
I encountered an issue with Postman. In order to attach a photo to the body, I had to switch over to the cloud agent. Then, in order to run a test using a localhost, I had to switch back over to desktop agent. This may be a pain point for some students. I have attached a screenshot of the bottom right corner of the postman app where I switch between agents. 
![postman](https://user-images.githubusercontent.com/57218090/123487694-10688380-d5d4-11eb-8c49-b482871300a0.PNG)

**Comment by emsesc** [comment]
@lazyplatypus I think we should make them use the Postman Desktop App

**Comment by creaturenex** [comment]
Added directions in Week 1 Step 3 to download app and to provided link to documentation.
Updated image in Week 1 step 4 showing postman desktop app and not browser postman tool.
There are other responses that mention postman but I did not think there was any value in changing all instances of Postman to say "Postman Desk App etc"
