### ISSUE TITLE
[Content Bug] Only lowercase file extensions accepted

### ISSUE THREAD

**Issue by dtetreau251** [bitprj/Intro-To-Serverless#328]
**Identify Steps:**
* Step 5

**Week:** 
Week 3

## Describe the Issue
When I was testing the download function for bunnimage in Postman, it would only work for files with lowercase file extensions.

## Proposed Fix 
 add a toLowerCase() or additional conditionals

**Comment by ganning127** [comment]
Hmm, I'm just curious how an uppercase file extension could happen. I think in week 3 step 2 the file extensions we test for and set are all lowercase?

```js
var filetype = parsedBody[0].type;
if (filetype == "image/png") {
    ext = "png";
} else if (filetype == "image/jpeg") {
    ext = "jpeg";
} else if (filetype == "image/jpg") {
    ext = "jpg"
} else {
    username = "invalidimage"
    ext = "";
}
```

**Comment by dtetreau251** [comment]
If the file you put in blob storage has an uppercase file extension, this function won't work with it. It only checks uppercase. I manually uploaded a few files into blob with uppercase extensions and it wouldn't get them.

**Comment by ganning127** [comment]
That's a good point David, but I think that since users won't be uploading images directly from their computer to the blob container, and will be going through your code to upload an image to the container, and since your code forces the filename to be lowercase, I don't think that this would be necessary.

**Comment by ganning127** [comment]
read above comment
